env:
  global:
    - CC_TEST_REPORTER_ID=19cd4efa77fdc8ca82e9308787980d32ec2282b88cd4d6f91d00528790b7fa09

cache:
  directories:
    - $HOME/.m2

language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk: oraclejdk8


